[build]
  base    = ""
  publish = "build"
  command = "npm run build"

[context.production]
  command = "STAGE=prod npm run build"

# Always redirect any request to our index.html
# and return the status code 200.
[[redirects]]
    from    = "/*"
    to      = "/"
    status  = 200
